[package]
name = "composable"
version = "0.6.0"
edition = "2021"

license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#futures = { version = "0.3.29", features = ["executor", "thread-pool"] }
futures = "0.3.29"
flume = { version = "0.11.0", features = ["select"], default-features = false }


[profile.release]
lto = "thin"
#debug = true

[profile.deployment]
inherits = "release"
codegen-units = 1
incremental = false
lto = "fat"
strip = true

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
