[package]
name = "composable"
version = "0.6.0"
edition = "2021"

readme = "README.md"
license = "MIT OR Apache-2.0"
include = ["LICENSE-APACHE.md", "LICENSE-MIT.md"]


[features]
# Use a spinlock internally. This feature mainly exists to demonstrate that
# the speed gains, if any, are inconsequential for a given application.
spin = ["flume/spin"]
# Supplies a “blocking” store that does not have its own internal thread.
blocking = []

# Features (in development) that are not yet part of SemVer.
unreleased = []
# Unreleased: View drawing and events.
views = ["lyon","svg","rustybuzz"]


[dependencies]
derive_reducers = { path = "src/derive_macros/derive_reducers" }
derive_more = { version = "1.0.0-beta", features = ["from", "try_into"], default-features = false }
lyon = { version = "1.0.1", optional = true, default-features = false }
rustybuzz = { version = "0.12.1", optional = true }
usvg = { version = "0.37.0", optional = true, default-features = false }
svg = { version = "0.14.0", optional = true, default-features = false }

flume = { git = "https://github.com/zesterer/flume.git", rev = "fcf3849", features = ["async"], default-features = false }
futures = { version = "0.3.29", features = ["executor"] }
smallvec = { version = "2.0.0-alpha" }

[dependencies.ttf-parser]
version = "*" # whatever rustybuzz is using…
features = ["std"] # enabled its `String` support
optional = true


[dev-dependencies]
ntest_timeout = "0.9.0"
divan = "0.1.8"
insta = "1.34.0"

winit = { version = "0.29.4" , features = ["rwh_05"] }
wgpu = "0.18.0"
muda = "0.11.2"

[target.'cfg(target_os = "windows")'.dependencies.windows-sys]
version = "0.52.0"


[profile.release]
debug = true
lto = "thin"

[profile.deployment]
inherits = "release"
codegen-units = 1
incremental = false
debug = false
strip = true
lto = "fat"

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3


[[bench]]
name = "sends"
harness = false

[[bench]]
name = "font_parsing"
harness = false


[[example]]
name = "winit"
required-features = ["blocking","views"]
