[package]
name = "composable"
version = "0.6.0"
edition = "2021"

readme = "README.md"
license = "MIT OR Apache-2.0"
include = ["LICENSE-APACHE.md", "LICENSE-MIT.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
spin = ["flume/spin"]

[dependencies]
futures = { version = "0.3.29", features = ["executor"] }
async-executor = { version = "1.6.0" }
once_cell = { version = "1.18.0" }

[dependencies.flume]
git = "https://github.com/bwoods/flume.git"
features = ["async"]
default-features = false

[dependencies.derive_more]
version = "0.99.17"
features = ["from", "try_into", "as_ref", "as_mut"]
default-features = false

[dev-dependencies]
ntest_timeout = "0.9.0"


[profile.release]
debug = true
lto = "thin"

[profile.deployment]
inherits = "release"
codegen-units = 1
incremental = false
debug = false
strip = true
lto = "fat"

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
