mod reactor;
mod wait;

use crate::Reducer;
pub(crate) use reactor::Reactor;
pub(crate) use reactor::Reason;

#[doc = include_str!("README.md")]
pub struct Store<State: Reducer, Event = <State as Reducer>::Action, Value = State> {
    reactor: Reactor<State, Event, Value>,
}

impl<State, Event, Value> Store<State, Event, Value>
where
    State: Reducer,
    Event: Send,
    Value: From<State> + Send + 'static,
{
    /// Creates a new `Store` with `state` as its initial state.
    pub fn with_initial(state: State) -> Self
    where
        State: Send + 'static,
        Event: Into<<State as Reducer>::Action> + Send + 'static,
    {
        Self {
            reactor: Reactor::new(|| state),
        }
    }

    /// Creates a new `Store` with its initial state generated by a function.
    /// Can be used if `State` is not [`Send`], but the arguments used to
    /// construct it are.
    pub fn new<F>(from: F) -> Self
    where
        State: Send + 'static,
        Event: Into<<State as Reducer>::Action> + Send + 'static,
        F: (FnOnce() -> State) + Send + 'static,
    {
        Self {
            reactor: Reactor::new(from),
        }
    }

    /// Shrinks the memory usage of the store as much as possible.
    pub fn shrink_to_fit(&mut self) {
        self.reactor.other.send(Reason::ShrinkToFit);
    }

    /// Calls the `Store`’s [`Reducer`][`crate::Reducer`] with `event`.
    ///
    /// `Event` are convertible into the `Reducer`’s `Action`s.
    pub fn send(&self, event: impl Into<Event>) {
        self.reactor.events.send(event.into())
    }

    /// Stops the `Store`’s runtime and returns its current `state` value.
    pub fn into_inner(self) -> Value {
        self.reactor.stop();
        self.reactor.handle.join().unwrap()
    }
}
