[package]
name = "composable-views"
edition.workspace = true
version.workspace = true
license.workspace = true

[features]
default = []


[dependencies]
composable.workspace = true
composable-dependencies.workspace = true
tracing.workspace = true
rustybuzz = "0.20.1"
lyon = "1.0.19"
svg = "0.18.0"

# [[bin]] dependencies
clap = { version = "4.3", features = ["derive"], optional = true }
usvg = { version = "0.47.0", optional = true }
convert_case = { version = "0.11.0", optional = true }

[dependencies.ui_id]
path = "src/ui_id"


[dev-dependencies]
insta.workspace = true
uuid = "1.23.4"


[[bin]]
name = "svg2path"
path = "src/shapes/bin.rs"
required-features = ["clap", "usvg", "convert_case"]
